### PR TITLE
Update eslintrc.json

### PR DESCRIPTION
**Pull request by georgebonnr**

### CODE REVIEW

**Comment by derekr** [comment]
What's the deal w/ this config change?

**Comment by georgebonnr** [comment]
don't need semi twice?

and extra semi seems like it should be a warning instead of an error

**Comment by georgebonnr** [comment]
also, what is the criteria for when something should be an error in linting vs. warning?

the noErrors plugin in webpack makes that a little dicey

**Comment by derekr** [comment]
Not sure. Something to talk about :D

**Comment by derekr** [comment]
Also note that master on the react codebase is locked in to a certain commit hash, but we can start pulling from master here now.

**Pull request merged**
